# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSTransformerCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers
  trans_mlp_features: 2048
  trans_num_encoder_layers: 3
  trans_num_decoder_layers: 3
  trans_dropout_p: 0.1
  trans_num_heads: 2
  trans_max_len: 2048

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
